### ISSUE TITLE
Restrictive Numba dependency makes Numpy type hints non-descriptive

### ISSUE THREAD

**Issue by mat100payette** [mjhydri/BeatNet#11]
Would it be possible now to update the dependency of Numba to a later version that supports numpy 1.23? Without it, type hints of `ndarray` is limited to just that, `ndarray`, when IDEs infer variable types. The later versions allow inferring `ndarray[shape, type]` such as `ndarray[(Any, 3), float]` which is very useful for code readability.

I'm aware of the restriction from librosa that was commented back in 2021, so just wondering if theit misleading (fake) support was fixed?

Feel free to close this if it's still not possible. Thanks.

**Comment by mjhydri** [comment]
Thank you so much, @mat100payette for pointing out this! I am aware that the newer numpy has several cool features that can be handy for both development and debugging. However, as you mentioned correctly, the versions of some of the dependencies are limited by some other dependencies. There are a few libraries like that and Librosa is one of them. In the case of Librosa, its used functionalities can be switched with some alternatives. Yet, more work needs to be done to make sure that none of the libraries have version conflicts with numpy 1.23.
