### ISSUE TITLE
why BeatNet SOTA model?

### ISSUE THREAD

**Issue by tricky61** [mjhydri/BeatNet#15]
in the "Temporal convolutional networks for musical audio beat tracking" of 2019, the published F-measure in ballroom、GTZAN are all better than BeatNet, so why BeatNet claimed SOTA?
is there something I missunderstand?

**Comment by mjhydri** [comment]
Of course, the part you misunderstood is the difference between online (Causal) models versus offline (Non-causal models) which are naturally different. For the former one, the future data is not available and both the neural network model and the inference algorithm should only use past data until the current point of time to infer the information while the latter one leverages all data points including the future to infer information. The BeatNet is SOFA online beat and downbeat tracking model while the one you mentioned is an offline model.
