### ISSUE TITLE
Incompatable with Spleeter?

### ISSUE THREAD

**Issue by davies-w** [mjhydri/BeatNet#20]
I was able to get it working but only by installing BeatNet *after* calling Spleeter, which makes it a little weird to work with. I have an open StackOverflow question on this, but I was wondering if you could resolve it with dependency management of some kind.

https://stackoverflow.com/questions/75838650/spleeter-and-beatnet-incompatible-numpy-numba-libraries-any-solutions

**Comment by boxabirds** [comment]
Alternatively use demucs -- much more reliable stemming https://github.com/facebookresearch/demucs -- though I've not tried it with beatnet yet.

**Comment by davies-w** [comment]
Actually, I was able to fix BeatNet - I basically removed the packaging, and manually installed the packages it needed. I don't know why the packaging doesn't work (I think its a bunch of outdated version information)

**Comment by davies-w** [comment]
This works for me in vanilla colab

!pip install -q cython
!pip install -q numba
!pip install -q librosa
!pip install -q mido
!pip install -q pytest
!pip install -q scipy
!pip install -q numpy
!pip install -q torch
!apt-get install portaudio19-dev
!pip install -q pyaudio
!pip install -q pydub
!pip install --upgrade --no-deps --force-reinstall --quiet 'git+https://github.com/CPJKU/madmom.git'
!pip install --upgrade --no-deps --force-reinstall --quiet 'git+https://github.com/davies-w/BeatNet.git'

**Comment by mjhydri** [comment]
In addition to the suggested solutions, in the case of Spleeter dependencies incompatibility, alternatives such as Demucs source separator engines can be utilized whose reported performance is higher than Spleeter.
