### ISSUE TITLE
Not speeding up inference on using CUDA/GPU

### ISSUE THREAD

**Issue by kewlcoder** [mjhydri/BeatNet#25]
hi @mjhydri / @karen-pal / @rlleshi ,

I am **able** to run the inference on GPU. It is successfully running but the speed is not faster than on CPU. It is slower at times as well.

**Config/Setup-** 
GPU - V100 16GB

Code used -
```
from BeatNet.BeatNet import BeatNet

estimator = BeatNet(1, mode='online', inference_model='PF', plot=['activations'], thread=False, device='cuda')

Output = estimator.process("audio file directory")

```

Also tried - 
```
from BeatNet.BeatNet import BeatNet

estimator = BeatNet(1, mode='online', inference_model='PF', plot=['activations'], thread=False, device='cuda:0')

Output = estimator.process("audio file directory")

```
Note that I checked whether [torch is recognizing the GPU](https://stackoverflow.com/questions/48152674/how-do-i-check-if-pytorch-is-using-the-gpu) or not. It is recognizing the GPU. Also, GPU memory consumption varies from 950 MB - 1350 MB  during inference.

**Comment by kewlcoder** [comment]
Hey @mjhydri,
Thanks for your inputs & suggestions. Really helpful.
1. Yes, I had already tried using plot = [] and the speed improved drastically :) .
2. Makes sense. My concern was that the GPU speed-up should be multiple times w.r.t. CPU. If that is not the case, we do not have a case/any motivation to use GPUs. So, summarily, I would resort to CPU itself. Also, on the "offline" suggestion, the tricky part is "offline" uses DBN. As much as I have understood from BeatNet's code, DBN is the model from Madmom. Now, Madmom's code is Commercially usable, but not the dataset and the model(if directly using data/model from their repo). If you can let me know **whether you are using their model or you have one custom trained ?**
3. That's a great suggestion. (min bpm, max bpm) seems to be a good parameter to play around with. Thanks !

**P.S. -** In the "Singing-vocal-Beat-Tracking" repo > issues I have replied to your comment. The **drive link** shared by you is not accessible. I have requested access for the same. Waiting for approval from you. Thanks

**Comment by kewlcoder** [comment]
Ok. Thanks. I have requested for access to the old link. If you can provide access, that would also work.
Also, since you mentioned you are not using Madmom's code or model, what is the source of your DBN model? Have you trained it yourself or using from some other source?

**Comment by mjhydri** [comment]
You are welcome. Please note that I have not received the access request yet. Please resend it again. Regarding your question, please note that as probably you know, DBN is an inference approach, not a neural network model that needs datasets to train. Therefore, for the offline inferences, DBN can be used on top of any of the BeatNet Neural networks which are trained on our datasets.
