### ISSUE TITLE
Not able to import beatnet

### ISSUE THREAD

**Issue by makkarss929** [mjhydri/BeatNet#30]
<img width="1512" alt="Screenshot 2023-11-08 at 1 18 33 PM" src="https://github.com/mjhydri/BeatNet/assets/41613183/e7722188-e84a-4f17-a04e-adba18dce2d5">

**Comment by mjhydri** [comment]
Madmom is one of the package dependencies that you need to make to have it installed before using BeatNet. Please refer to the readme file and the installation instructions.
