### ISSUE TITLE
Make pyaudio optional?

### ISSUE THREAD

**Issue by carlthome** [mjhydri/BeatNet#31]
Noticed that pyaudio is a required installation even when not using audio streaming, because it's imported in the top-level BeatNet.py module. Could this be relaxed to an optional dependency?

**Comment by mjhydri** [comment]
Thanks for your suggestion. Please note that one of the main features of BeatNet is real-time capability, often coupled with a streaming feature. To support this functionality, we have chosen to include pyaudio as a dependency. If you do not require streaming or face installation restrictions for Pyaudio, you can either use the GitHub repository installation with an edited requirements file or create a private pip test PyPI package with edited requirements.

**Comment by carlthome** [comment]
>you can either use the GitHub repository installation with an edited requirements file or create a private pip test PyPI package with edited requirements.

No, this won't work since the import statement remains in the source.

**Comment by mjhydri** [comment]
By using the GitHub repository to create a pip test, the assumption is to comment the Pyaudio import statement as well as the streaming call in the function.

**Comment by not-matt** [comment]
https://github.com/not-matt/BeatNet

@carlthome my fork removes pyaudio
