### ISSUE TITLE
Can you please provide the annotation using which you have validated the model as I am not able to reproduce rest on GTZAN dataset?

### ISSUE THREAD

**Issue by tanish-g** [mjhydri/BeatNet#4]
Can you provide Rock Corpus Annotation and Ballroom Annotations also?

**Comment by tanish-g** [comment]
GTZAN Dataset annotation ,Ballroom Dataset annotations and  Rock Corpus Dataset Annotation also?

**Comment by mjhydri** [comment]
The required material is sent to you!

**Comment by cnlinxi** [comment]
I also want to use this dataset for evaluation. Can you provide me with a copy, thanks
@mjhydri
