### ISSUE TITLE
PyAudio Input overflowed

### ISSUE THREAD

**Issue by AltinayGrass** [mjhydri/BeatNet#7]
Hello,

I can run with below modification.

--------
  def activation_extractor_stream(self):
        # TODO: 
        ''' Streaming window
        Given the training input window's origin set to center, this streaming data formation causes 0.084 (s) delay compared to the trained model that needs to be fixed. 
        '''   
        with torch.no_grad():
            
                    hop = self.stream.read(self.log_spec_hop_length,exception_on_overflow = False)
--------

**Comment by mjhydri** [comment]
In case of input overflow,  setting the"exception_on_overflow = False" keyword parameter perfectly works! It will be added in the next release! Thank you!
