### ISSUE TITLE
llvmlite error during installation

### ISSUE THREAD

**Issue by Chris-Danikas** [mjhydri/BeatNet#8]
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> llvmlite

I don't know what's wrong with this package

**Comment by mjhydri** [comment]
llvmlite is a dependency for Numba which is a requirement for our package. According to its maintainers though, It is not compatible with newer versions of python yet. So, here we provide two solutions as follows:

1-	Try to install our package with former versions of python e.g. Python 3.8
2-	Install llvmlite manually before installing our package using the following code: pip3 install llvmlite==0.31.0
